### ISSUE TITLE
These error is showing me. how to solve these ?

### ISSUE THREAD

**Issue by asmallick1999** [asmallick1999/PostApiPractice#1]
![image](https://user-images.githubusercontent.com/84728108/224043671-3c18ac04-d58d-4f09-9ba3-d7d33612e746.png)

The backend is working perfectly fine

**Comment by asmallick1999** [comment]
one problem solved after adding thead and tbody
but still having this issue 
![image](https://user-images.githubusercontent.com/84728108/224049468-2c795453-ec4e-4e47-8c5a-061cb6fce31d.png)

**Comment by Jay-study-nildana** [comment]
@asmallick1999 

See if you can move this question to 

https://github.com/Jay-study-nildana/NodeJSForStudents/issues

and, link to this repository from there.

Thanks :)

**Comment by asmallick1999** [comment]
Sure, I will do it

**Comment by Jay-study-nildana** [comment]
You forgot to put the link here, he he :) I am putting it here.

https://github.com/Jay-study-nildana/NodeJSForStudents/issues/5

There you go.

Now, after you see this comment, "close this issue"

Excellent.

Jay.

**Comment by asmallick1999** [comment]
Oops sorry,
ok I am closing the issue
